import { TraitImageMap, TraitType } from "@/types/traits";

// Map of all available trait images
export const traitImageMap: TraitImageMap = {
  clothes: {
    "1": { path: "1.png" },
    "2": { path: "2.png" },
    "3": { path: "3_front.png", hasBack: true },
    "4": { path: "4.png" },
    "5": { path: "5.png" },
    "6": { path: "6.png" },
    "7": { path: "7.png" },
    "8": { path: "8.png" },
    "9": { path: "9.png" },
    "10": { path: "10.png" },
    "11": { path: "11.png" },
    "12": { path: "12.png" },
    "13": { path: "13.png" },
    "14": { path: "14.png" },
    "15": { path: "15.png" },
    "16": { path: "16.png" },
    "17": { path: "17.png" },
    "18": { path: "18.png" },
    "19": { path: "19.png" },
    "20": { path: "20.png" },
    "21": { path: "21.png" },
    "22": { path: "22.png" },
    "23": { path: "23.png" },
    "24": { path: "24.png" },
    "25": { path: "25.png" },
    "26": { path: "26.png" },
    "27": { path: "27.png" },
    "28": { path: "28.png" },
    "29": { path: "29.png" },
    "30": { path: "30.png" },
    "31": { path: "31.png" },
    "32": { path: "32.png" },
    "33": { path: "33.png" },
    "34": { path: "34.png" },
    "35": { path: "35_front.png", hasBack: true },
    "36": { path: "36.png" },
    "37": { path: "37.png" },
    "38": { path: "38.png" },
    "39": { path: "39.png" },
    "40": { path: "40.png" },
    "41": { path: "41.png" },
    "42": { path: "42.png" },
    "43": { path: "43.png" },
    "44": { path: "44.png" },
    "45": { path: "45.png" },
    "46": { path: "46.png" },
    "47": { path: "47.png" },
    "48": { path: "48.png" },
    "49": { path: "49.png" },
    "50": { path: "50.png" },
    "51": { path: "51.png" },
    "52": { path: "52.png" },
    "53": { path: "53.png" },
    "54": { path: "54.png" },
    "55": { path: "55.png" },
    "56": { path: "56.png" },
    "57": { path: "57.png" },
    "58": { path: "58.png" },
    "59": { path: "59.png" },
    "60": { path: "60.png" },
    "61": { path: "61.png" },
    "62": { path: "62.png" },
    "63": { path: "63.png" },
    "64": { path: "64.png" },
  },
  hair: {
    "1": { path: "1.png" },
    "2": { path: "2.png" },
    "3": { path: "3.png" },
    "4": { path: "4_front.png", hasBack: true },
    "6": { path: "6.png" },
    "10": { path: "10.png" },
    "11": { path: "11_front.png", hasBack: true },
    "12": { path: "12_front.png", hasBack: true },
    "13": { path: "13.png" },
    "16": { path: "16.png" },
    "17": { path: "17_front.png", hasBack: true },
    "18": { path: "18_front.png", hasBack: true },
    "19": { path: "19.png" },
    "21": { path: "21.png" },
    "22": { path: "22_front.png", hasBack: true },
    "23": { path: "23.png" },
    "24": { path: "24.png" },
    "26": { path: "26.png" },
    "27": { path: "27_front.png", hasBack: true },
    "28": { path: "28.png" },
    "29": { path: "29.png" },
    "30": { path: "30_front.png", hasBack: true },
    "31": { path: "31_front.png", hasBack: true },
    "32": { path: "32.png" },
    "33": { path: "33.png" },
    "38": { path: "38.png" },
    "43": { path: "43_front.png", hasBack: true },
    "50": { path: "50_front.png", hasBack: true },
    "51": { path: "51.png" },
    "58": { path: "58.png" },
    "60": { path: "60.png" },
    "61": { path: "61.png" },
    "62": { path: "62_front.png", hasBack: true },
    "63": { path: "63_front.png", hasBack: true },
  },
  skin: {
    "1": { path: "1.png" },
    "2": { path: "2.png" },
    "3": { path: "3.png" },
    "4": { path: "4.png" },
    "5": { path: "5.png" },
    "6": { path: "6.png" },
  },
  ear: {
    "1": { path: "1.png" },
    "2": { path: "2.png" },
    "12": { path: "12.png" },
    "22": { path: "22.png" },
    "26": { path: "26.png" },
    "33": { path: "33.png" },
    "34": { path: "34.png" },
    "35": { path: "35.png" },
  },
  eyeball: {
    "1": { path: "1.png" },
    "2": { path: "2.png" },
    "3": { path: "3.png" },
    "4": { path: "4.png" },
    "5": { path: "5.png" },
    "6": { path: "6.png" },
    "7": { path: "7.png" },
    "9": { path: "9.png" },
    "11": { path: "11.png" },
    "15": { path: "15.png" },
    "16": { path: "16.png" },
    "17": { path: "17.png" },
    "20": { path: "20.png" },
    "21": { path: "21.png" },
    "22": { path: "22.png" },
    "26": { path: "26.png" },
    "29": { path: "29.png" },
    "31": { path: "31.png" },
  },
  eyeliner: {
    "1": { path: "1.png" },
    "4": { path: "4.png" },
    "6": { path: "6.png" },
    "7": { path: "7.png" },
    "8": { path: "8.png" },
    "11": { path: "11.png" },
    "16": { path: "16.png" },
    "19": { path: "19.png" },
    "22": { path: "22.png" },
    "23": { path: "23.png" },
    "26": { path: "26.png" },
    "28": { path: "28.png" },
    "31": { path: "31.png" },
    "32": { path: "32.png" },
  },
  eyebrow: {
    "1": { path: "1.png" },
    "2": { path: "2.png" },
    "9": { path: "9.png" },
    "11": { path: "11.png" },
    "13": { path: "13.png" },
    "17": { path: "17.png" },
    "18": { path: "18.png" },
    "19": { path: "19.png" },
    "23": { path: "23.png" },
    "25": { path: "25.png" },
    "26": { path: "26.png" },
    "27": { path: "27.png" },
    "28": { path: "28.png" },
    "29": { path: "29.png" },
    "30": { path: "30.png" },
  },
  head: {
    "33": { path: "33.png" },
    "34": { path: "34.png" },
    "35": { path: "35.png" },
  },
  face: {
    "33": { path: "33.png" },
    "34": { path: "34.png" },
  },
  eyelid: {
    "1_1": { path: "1_1.png" },
    "1_2": { path: "1_2.png" },
    "1_3": { path: "1_3.png" },
    "1_4": { path: "1_4.png" },
    "1_5": { path: "1_5.png" },
    "1_6": { path: "1_6.png" },
    "28_1": { path: "28_1.png" },
    "28_2": { path: "28_2.png" },
    "28_3": { path: "28_3.png" },
    "28_4": { path: "28_4.png" },
    "28_5": { path: "28_5.png" },
    "28_6": { path: "28_6.png" },
    "32_1": { path: "32_1.png" },
    "32_2": { path: "32_2.png" },
    "32_3": { path: "32_3.png" },
    "32_4": { path: "32_4.png" },
    "32_5": { path: "32_5.png" },
    "32_6": { path: "32_6.png" },
  },
  eyewhite: {
    "0": { path: "0.png" },
    "6": { path: "6.png" },
    "28": { path: "28.png" },
  },
  mouth: {
    "0": { path: "0.png" },
    "1": { path: "1.png" },
    "2": { path: "2.png" },
    "4": { path: "4.png" },
    "12": { path: "12.png" },
    "21": { path: "21.png" },
    "27": { path: "27.png" },
    "28": { path: "28.png" },
    "29": { path: "29.png" },
    "30": { path: "30.png" },
  },
  eyeliner_for_skin_2: {
    "1": { path: "1.png" },
    "4": { path: "4.png" },
    "6": { path: "6.png" },
    "7": { path: "7.png" },
    "8": { path: "8.png" },
    "11": { path: "11.png" },
    "16": { path: "16.png" },
    "19": { path: "19.png" },
    "22": { path: "22.png" },
    "23": { path: "23.png" },
    "26": { path: "26.png" },
    "28": { path: "28.png" },
    "31": { path: "31.png" },
    "32": { path: "32.png" },
  },
  eyeliner_for_skin_3: {
    "1": { path: "1.png" },
    "4": { path: "4.png" },
    "6": { path: "6.png" },
    "7": { path: "7.png" },
    "8": { path: "8.png" },
    "11": { path: "11.png" },
    "16": { path: "16.png" },
    "19": { path: "19.png" },
    "22": { path: "22.png" },
    "23": { path: "23.png" },
    "26": { path: "26.png" },
    "28": { path: "28.png" },
    "31": { path: "31.png" },
    "32": { path: "32.png" },
  },
  eyebrow_for_skin_3: {
    1: { path: "1.png" },
    2: { path: "2.png" },
    9: { path: "9.png" },
    11: { path: "11.png" },
    13: { path: "13.png" },
    17: { path: "17.png" },
    18: { path: "18.png" },
    19: { path: "19.png" },
    23: { path: "23.png" },
    25: { path: "25.png" },
    26: { path: "26.png" },
    27: { path: "27.png" },
    28: { path: "28.png" },
    29: { path: "29.png" },
    30: { path: "30.png" },
  },
  mouth_for_skin_3: {
    0: { path: "0.png" },
    1: { path: "1.png" },
    2: { path: "2.png" },
    30: { path: "30.png" },
  },
  background: {
    Mega: { path: "@pfpbg.png" },
    GTE: { path: "bg-GTE.jpg" },
    MegaDark: { path: "bg-mega-dark.jpg" },
    MegaLight: { path: "bg-mega-light.jpg" },
    Noise: { path: "bg-noise.jpg" },
    Teko: { path: "bg-teko.jpg" },
    Vahalla: { path: "bg-vahalla.jpg" },
    Cap: { path: "bg-cap.jpg" },
    Hop: { path: "bg-hop.jpg" },
    SpaceBust: { path: "bg-space-portrait.png" },
    SpaceFull: { path: "bg-space-full.png" },
    SmolBust: { path: "bg-smolmega-portrait.png" },
    SmolFull: { path: "bg-smolmega-full.png" },
  },
};

const CDN_URL = "https://fluffle-traits.b-cdn.net";

export function getTraitImageUrl(type: TraitType, id: string): string {
  const traitInfo = traitImageMap[type]?.[id];
  if (!traitInfo) {
    if (process.env.NODE_ENV === "development") {
      console.warn(`No trait found for type ${type} and id ${id}`);
    }
    return "";
  }

  // If the path starts with '@', it's a local file
  if (traitInfo.path.startsWith("@")) {
    return `/${traitInfo.path.slice(1)}`; // Remove the @ and add leading slash
  }

  // Special case for backgrounds - use 'backgrounds' directory
  const directory = type === "background" ? "backgrounds" : type;
  return `${CDN_URL}/traits/${directory}/${traitInfo.path}`;
}

export function getTraitBackImageUrl(
  type: TraitType,
  id: string
): string | null {
  const traitInfo = traitImageMap[type]?.[id];
  if (!traitInfo?.hasBack) {
    return null;
  }

  return `${CDN_URL}/traits/${type}/${id}_back.png`;
}

export function isValidTrait(type: TraitType, id: string): boolean {
  return !!traitImageMap[type]?.[id];
}

export function getAvailableTraitIds(type: TraitType): string[] {
  return Object.keys(traitImageMap[type] || {});
}
